### ISSUE TITLE
MVI + Flow

### ISSUE THREAD

**Issue by roquebuarquejr** [androiddevbr/sugestoes-temas#18]
* **Tema sugerido:** Entendendo a arquitetura MVI com Flow.
* **Descrição:** Existem diversas arquiteturas no mundo Android hoje em dia, a mais vista entre elas é a MVVM que utiliza programação imperativa. Nessa palestra vamos falar sobre MVI e como criar uma arquitetura reative utilizando um fluxo unidirecional entre as ações do usuário e os diferentes estados apresentados na tela.

* **Indicação de participante:** Roque Buarque @roqbjr

**Comment by orafaaraujo** [comment]
Fala, @RBJUR, beleza?

Qual formato você acha que este conteúdo ficaria legal?

Abraços!

**Comment by roquebuarquejr** [comment]
@orafaaraujo fui informado que a duracao sera de 1h, estou preparando material para 40min de slides + 20min show case.

**Comment by anacoimbrag** [comment]
[Meetup](https://www.meetup.com/androiddevbr/events/274537657/) marcado para 25/11 - 19h Obrigada por contribuir com a comunidade @RBJUR!
