### ISSUE TITLE
Construindo para Escalar - MVP / Modularização / Responsabilidade Unica

### ISSUE THREAD

**Issue by Canato** [androiddevbr/sugestoes-temas#19]
* **Tema sugerido:** Construindo para Escalar - MVP / Modularização / Responsabilidade Unica
* **Descrição:** Durante anos as melhores práticas de desenvolvimento eram focadas no BackEnd e no FrontEnd, mas como ressignificar essas práticas para o mundo mobile? Uma apresentação que visa trazer um dos lados da construção de um aplicativo Android que seja escalável e respeite o universo de desenvolvimento.
* **Plataforma:** 
- [ ] :writing_hand: [Medium](https://canato.medium.com/)
- [ ] :studio_microphone: [Conhecimento Util Podcast](anchor.fm/conhecimentoutil) (não é sobre android)
- [ ] :sparkles: [OpenSource](https://github.com/CanHub/Android-Image-Cropper)
* **Indicação de participante:** @canato
* **Mais informações:** 
[Similar talk I did on Londroid](https://www.youtube.com/watch?v=pxBNyLZiIVI&t=12s&ab_channel=Canato)

**Comment by roquebuarquejr** [comment]
Fala @Canato blz?

Obrigado por atender a chamada para speakers, muito bom ter vc conosco em nosso meetup :) 
Vc tem alguma data de sua preferencia para apresentar esse conteúdo? 
Sabe mais ou menos o tempo de duraçao ta talk? 

Abs 
Roque

**Comment by Canato** [comment]
@RBJUR estou trocando de empresa então a vida ta aquela loucura, poderia ser mais pro meio de Março ?

**Comment by roquebuarquejr** [comment]
Claro mano, quando for melhor pra vc, vou deixar on hold por enquanto e a gente vai dando continuidade mais pra frente.

**Comment by roquebuarquejr** [comment]
@Canato bora continuar com esse tópico?

**Comment by Canato** [comment]
> @Canato bora continuar com esse tópico? 

Timing perfeito hahaha assinei ontem com a nova empresa. Vamos fazer pro final do mês?

Só o tempo de agilizar os slides :D.

Vai ser modelo talk/apresentação com Q&A no final?

Ou pensaram em algo diferente? Tipo gravação de podcast ao vivo e discussão mais que apresentação? 

Tô pilhando todos hahahah

**Comment by roquebuarquejr** [comment]
Cara bora fazer talk/apresentação com Q&A no final dessa vez e podemos pensar em algum outro modelo para dar continuidade nas perguntas talvez mais pra frente.

Essa palestra é a mesma que vc mandou o link? Vai ser sobre MVP no Android?

Outra pergunta, tem dia e horario melhor pra vc?

**Comment by Canato** [comment]
Sim, vai ser bem parecido com a do link. 
Mas j'a aprendi umas coisas de l'a pra ca hahahah (inclusive, logo inicio meu trabalho full MVI)

Vamos fazer dia 30/3? 18h Brasil seria um bom horario?

**Comment by roquebuarquejr** [comment]
@Canato fechado, dia 30/3 as 18h horario do BR.

Vamos seguir e criar o evento do nosso lado, qualquer atualização eu deixo vc saber.

Abs

**Comment by Canato** [comment]
Done, beauty 😭
