### ISSUE TITLE
Como ser um iniciante aos 30

### ISSUE THREAD

**Issue by brunohensel** [androiddevbr/sugestoes-temas#21]
* **Tema sugerido:**  Experiência pessoal como iniciante.
* **Descrição:** Estou trabalhando na área há pouco mais de 1 ano e meio, conclui recentemente o Nanodegree pela Udacity em parceiria com o Google, antes trabalhava como advogado. Atualmente moro na Alemanha. Gostaria de compartilhar um pouco como foi iniciar aos 30 anos de idade, os medos e inseguranças e a importância de ter alguém como mentor como forma de acelerar seu desenvolvimento.
* **Plataforma:** 
- [ ] :video_camera: Youtube/Meetup
* **Indicação de participante:** Roque @RBJUR e Eu rs.

**Comment by roquebuarquejr** [comment]
Evento cancelado
